return {}
-- return {
--   {
--     'yetone/avante.nvim',
--     -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--     -- ⚠️ must add this setting! ! !
--     build = vim.fn.has 'win32' ~= 0 and 'powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false' or 'make',
--     event = 'VeryLazy',
--     version = false, -- Never set this value to "*"! Never!
--     opts = {
--       -- add any opts here
--       -- this file can contain specific instructions for your project
--       instructions_file = 'avante.md',
--       selection = {
--         enabled = false,
--       },
--       selector = {
--         provider = 'snacks',
--       },
--       input = {
--         provider = 'snacks',
--         provider_opts = {
--           title = 'Avante Input',
--           icon = ' ',
--         },
--       },
--       -- for example
--       provider = 'claude',
--       providers = {
--         claude = {
--           endpoint = 'https://api.anthropic.com',
--           model = 'claude-sonnet-4-20250514',
--           timeout = 30000, -- Timeout in milliseconds
--           extra_request_body = {
--             temperature = 0.75,
--             max_tokens = 20480,
--           },
--         },
--       },
--     },
--     dependencies = {
--       'nvim-lua/plenary.nvim',
--       'MunifTanjim/nui.nvim',
--       'folke/snacks.nvim',
--       {
--         'MeanderingProgrammer/render-markdown.nvim',
--         opts = {
--           file_types = { 'markdown', 'Avante' },
--         },
--         ft = { 'markdown', 'Avante' },
--       },
--     },
--   },
-- }
