return {
  -- -- Quarto support for data science
  -- {
  --   'quarto-dev/quarto-nvim',
  --   ft = { 'quarto' },
  --   opts = {
  --     codeRunner = {
  --       enabled = true,
  --       default_method = "molten",
  --     },
  --   },
  --   dependencies = {
  --     'jmbuhr/otter.nvim',               -- For language features in code cells
  --     'nvim-treesitter/nvim-treesitter', -- Syntax highlighting and code understanding
  --   },
  -- },
  --
  -- -- Jupytext integration for working with Jupyter notebooks
  -- {
  --   'GCBallesteros/jupytext.nvim',
  --   opts = {
  --     custom_language_formatting = {
  --       python = { extension = 'qmd', style = 'quarto', force_ft = 'quarto' },
  --       r = { extension = 'qmd', style = 'quarto', force_ft = 'quarto' },
  --     },
  --   },
  -- },
  --
  -- -- Image management and clipboard integration
  -- {
  --   'HakonHarnes/img-clip.nvim',
  --   event = 'BufEnter',
  --   ft = { 'markdown', 'quarto', 'latex' },
  --   opts = {
  --     default = { dir_path = 'img' },
  --     filetypes = {
  --       markdown = { url_encode_path = true, template = '![$CURSOR]($FILE_PATH)' },
  --       quarto = { url_encode_path = true, template = '![$CURSOR]($FILE_PATH)' },
  --     },
  --   },
  --   config = function(_, opts)
  --     require('img-clip').setup(opts)
  --     vim.keymap.set('n', '<leader>ii', ':PasteImage<cr>', { desc = 'Insert image from clipboard' })
  --   end,
  -- },
  --
  -- -- Equation preview in markdown/quarto files
  -- {
  --   'jbyuki/nabla.nvim',
  --   keys = {
  --     { '<leader>qm', ':lua require"nabla".toggle_virt()<cr>', { desc = 'Toggle math equations' } },
  --   },
  -- },
  --
  -- -- Molten for interactive code execution
  -- {
  --   'benlubas/molten-nvim',
  --   enabled = true,
  --   build = ':UpdateRemotePlugins',
  --   init = function()
  --     vim.g.molten_image_provider = 'image.nvim'
  --     vim.g.molten_output_win_max_height = 20
  --     vim.g.molten_auto_open_output = false
  --   end,
  --   keys = {
  --     { 'n', '<leader>mi', ':MoltenInit<cr>',                { desc = 'Molten init' } },
  --     { 'v', '<leader>mv', ':<C-u>MoltenEvaluateVisual<cr>', { desc = 'Evaluate visual selection' } },
  --     { 'n', '<leader>mr', ':MoltenReevaluateCell<cr>',      { desc = 'Re-evaluate cell' } },
  --   },
  -- },
}

