require('lazy').setup {
  { import = 'custom.plugins.ai' },
  { import = 'custom.plugins.lsp' },
  { import = 'custom.plugins.format' },
  { import = 'custom.plugins.telescope' },
  { import = 'custom.plugins.treesitter' },
  { import = 'custom.plugins.which-key' },
  { import = 'custom.plugins.autopairs' },
  { import = 'custom.plugins.blink' },
  { import = 'custom.plugins.bufferline' },
  { import = 'custom.plugins.colorscheme' },
  { import = 'custom.plugins.dadbod' },
  { import = 'custom.plugins.doc' },
  { import = 'custom.plugins.git' },
  { import = 'custom.plugins.icons' },
  { import = 'custom.plugins.indent-blankline' },
  { import = 'custom.plugins.lint' },
  { import = 'custom.plugins.lualine' },
  { import = 'custom.plugins.oil' },
  { import = 'custom.plugins.test' },
  { import = 'custom.plugins.tmux-navigator' },
}
