vim.keymap.set("n", "<leader>gs", ":G<CR>")
vim.keymap.set("n", "<leader>gh", ":diffget //3<CR>")
vim.keymap.set("n", "<leader>gu", ":diffget //2<CR>")
vim.keymap.set("n", "<leader>gc", ":GCheckout<CR>")
vim.keymap.set("n", "<leader>ga", ":G add %:p<CR><CR>")
vim.keymap.set("n", "<leader>gc", ":G commit -v -q<CR>")
vim.keymap.set("n", "<leader>gt", ":G commit -v -q %:p<CR>")
vim.keymap.set("n", "<leader>gff", ":G ff<CR>")
vim.keymap.set("n", "<leader>gfo", ":G fetch origin<CR>")
vim.keymap.set("n", "<leader>gd", ":Gdiff<CR>")
vim.keymap.set("n", "<leader>ge", ":Gedit<CR>")
vim.keymap.set("n", "<leader>gr", ":Gread<CR>")
vim.keymap.set("n", "<leader>grb", ":G rebase -i<CR>")
vim.keymap.set("n", "<leader>gw", ":Gwrite<CR><CR>")
vim.keymap.set("n", "<leader>gl", ":silent! Glog<CR>:bot copen<CR>")
vim.keymap.set("n", "<leader>gp", ":Ggrep<Space>")
vim.keymap.set("n", "<leader>gm", ":Gmove<Space>")
vim.keymap.set("n", "<leader>gbl", ":G blame<CR>")
vim.keymap.set("n", "<leader>go", ":G checkout<Space>")
vim.keymap.set("n", "<leader>gps", ":Dispatch! git push<CR>")
vim.keymap.set("n", "<leader>gpl", ":Dispatch! git pull<CR>")
