blank_issues_enabled: false

contact_links:
  - name: Help
    url: https://github.com/nvim-lua/kickstart.nvim/discussions/categories/q-a
    about: Ask the community for help

  - name: Ideas
    url: https://github.com/nvim-lua/kickstart.nvim/discussions/categories/ideas
    about: Share ideas for new features
