return { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  event = 'VimEnter', -- Sets the loading event to 'VimEnter'
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    -- Document existing key chains
    spec = {
      { '<leader>c', group = '[C]ode', desc = {
        a = 'Code [A]ction',
        f = '[F]ormat buffer',
      }},
      { '<leader>d', group = '[D]ocument', desc = {
        x = 'Document [D]iagnostics',
        s = 'Document [S]ymbols',
        [''] = 'Show diagnostic under cursor',
      }},
      { '<leader>s', group = '[S]earch', desc = {
        h = '[H]elp',
        k = '[K]eymaps',
        f = '[F]iles',
        s = '[S]elect Telescope',
        w = 'Current [W]ord',
        g = '[G]rep',
        d = '[D]iagnostics',
        r = '[R]esume last search',
        ['/'] = 'Search in open files',
        n = '[N]eovim config files',
      }},
      { '<leader>w', group = '[W]orkspace', desc = {
        s = '[S]ymbols',
      }},
      { '<leader>t', group = '[T]oggle', desc = {
        h = 'Toggle inlay [H]ints',
      }},
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>g', group = '[G]it', desc = {
        s = 'Status',
      }},
      { '<leader>f', group = '[F]ile Explorer', desc = {
        e = 'Toggle explorer',
        f = 'Focus explorer',
      }},
      { '<leader>n', group = '[N]otifications', desc = {
        n = 'Toggle notifications',
        h = 'Notification [H]istory',
        c = '[C]lear notifications',
      }},
      { '<leader>p', group = 'Debug/[P]rofile', desc = {
        b = 'Toggle [B]reakpoint',
        c = '[C]ontinue debugging',
        n = 'Step over ([N]ext)',
        i = 'Step [I]nto',
        o = 'Step [O]ut',
        r = 'Open [R]EPL',
        l = 'Run [L]ast debug session',
        x = 'Toggle debug UI',
      }},
      { '<leader>b', group = '[B]uffer', desc = {
        p = '[P]revious',
        n = '[N]ext',
        d = '[D]elete',
        D = 'Force [D]elete',
      }},
      { '<leader>q', desc = 'Open diagnostic [Q]uickfix list' },
      { '<leader>e', desc = 'Toggle file [E]xplorer' },
      { '<leader>o', desc = 'F[o]cus file explorer' },
      { '<leader>x', desc = 'Close buffer' },
      { '<leader>X', desc = 'Force close buffer' },
      { '<leader>/', desc = 'Search in current buffer' },
      { '<leader><leader>', desc = 'Find buffers' },
    },
  },
}
