return {}
--   dap = {
--     plugin = true,
--     n = {
--       ['<leader>db'] = {
--         '<cmd> DapToggleBreakpoint <CR>',
--         'Add breakpoint at line',
--       },
--       ['<leader>dus'] = {
--         function()
--           local widgets = require('dap.ui.widgets')
--           local sidebar = widgets.sidebar(widgets.scopes)
--           sidebar.open()
--         end,
--         'Open debugging sidebar',
--       },
--     },
--   },
--   dap_go = {
--     plugin = true,
--     n = {
--       ['<leader>dgt'] = {
--         function()
--           require('dag-go').debug_test()
--         end,
--         'Debug go test',
--       },
--       ['<leader>dgl'] = {
--         function()
--           require('dap-go').debug_last()
--         end,
--         'Debug last go test',
--       },
--     },
--   },
-- }
