# copied from gbprod/yanky.nvim
name: Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: '0 7 * * 1'
     # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nvim-versions: ['stable', 'nightly']
        steps:
            - name: Install NeoVim
            - uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: ${{ matrix.nvim-versions }}
            - name: Checkout
            - uses: actions/checkout@v3
            - name: Setup kitckstart and start nvim
              run: |
                ln -sf $GITHUB_WORKSPACE "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
                touch msg.log
                nvim --headless -c ':Lazy! sync' -c ':qa' init.lua 2>&1 | tee -a msg.log
                nvim --headless -c ':checkhealth' -c ':qa' init.lua 2>&1 | tee -a msg.log
                echo -e '\n++++++++++++++++++++++++++++++'
                cat msg.log
                echo -e '++++++++++++++++++++++++++++++\n'
                grep -i 'error' msg.log
                if [ $? -eq 0 ]; then
                  exit 1
                else
                    exit 0
                fi

    stylua-check:
        name: Check codestyle
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Stylua Check
              uses: JohnnyMorganz/stylua-action@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  version: latest
                  args: --check .
