# Check Lua Formatting
name: Check Lua Formatting
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stylua-check:
    if: github.repository == 'nvim-lua/kickstart.nvim'
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
